# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compute.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompute.proto\x12\x04\x64\x65mo\"0\n\x0e\x43omputeRequest\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0f\n\x07work_ms\x18\x02 \x01(\x05\"M\n\x0f\x43omputeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\";\n\x10TransformRequest\x12\x16\n\x0e\x63omputed_value\x18\x01 \x01(\x05\x12\x0f\n\x07work_ms\x18\x02 \x01(\x05\"O\n\x11TransformResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\">\n\x10\x41ggregateRequest\x12\x19\n\x11transformed_value\x18\x01 \x01(\x05\x12\x0f\n\x07work_ms\x18\x02 \x01(\x05\"Q\n\x11\x41ggregateResponse\x12\x14\n\x0c\x66inal_result\x18\x01 \x01(\x05\x12\x10\n\x08pipeline\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x32\xc3\x01\n\x07\x43ompute\x12\x38\n\x07\x43ompute\x12\x14.demo.ComputeRequest\x1a\x15.demo.ComputeResponse\"\x00\x12>\n\tTransform\x12\x16.demo.TransformRequest\x1a\x17.demo.TransformResponse\"\x00\x12>\n\tAggregate\x12\x16.demo.AggregateRequest\x1a\x17.demo.AggregateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compute_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COMPUTEREQUEST']._serialized_start=23
  _globals['_COMPUTEREQUEST']._serialized_end=71
  _globals['_COMPUTERESPONSE']._serialized_start=73
  _globals['_COMPUTERESPONSE']._serialized_end=150
  _globals['_TRANSFORMREQUEST']._serialized_start=152
  _globals['_TRANSFORMREQUEST']._serialized_end=211
  _globals['_TRANSFORMRESPONSE']._serialized_start=213
  _globals['_TRANSFORMRESPONSE']._serialized_end=292
  _globals['_AGGREGATEREQUEST']._serialized_start=294
  _globals['_AGGREGATEREQUEST']._serialized_end=356
  _globals['_AGGREGATERESPONSE']._serialized_start=358
  _globals['_AGGREGATERESPONSE']._serialized_end=439
  _globals['_COMPUTE']._serialized_start=442
  _globals['_COMPUTE']._serialized_end=637
# @@protoc_insertion_point(module_scope)
