# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import compute_pb2 as compute__pb2


class ComputeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compute = channel.unary_unary(
                '/demo.Compute/Compute',
                request_serializer=compute__pb2.ComputeRequest.SerializeToString,
                response_deserializer=compute__pb2.ComputeResponse.FromString,
                )
        self.Transform = channel.unary_unary(
                '/demo.Compute/Transform',
                request_serializer=compute__pb2.TransformRequest.SerializeToString,
                response_deserializer=compute__pb2.TransformResponse.FromString,
                )
        self.Aggregate = channel.unary_unary(
                '/demo.Compute/Aggregate',
                request_serializer=compute__pb2.AggregateRequest.SerializeToString,
                response_deserializer=compute__pb2.AggregateResponse.FromString,
                )
        self.Refine = channel.unary_unary(
                '/demo.Compute/Refine',
                request_serializer=compute__pb2.RefineRequest.SerializeToString,
                response_deserializer=compute__pb2.RefineResponse.FromString,
                )
        self.Finalize = channel.unary_unary(
                '/demo.Compute/Finalize',
                request_serializer=compute__pb2.FinalizeRequest.SerializeToString,
                response_deserializer=compute__pb2.FinalizeResponse.FromString,
                )


class ComputeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Compute(self, request, context):
        """Service A: Compute - performs computation on input
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transform(self, request, context):
        """Service B: Transform - transforms the computed result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Aggregate(self, request, context):
        """Service C: Aggregate - aggregates results and returns final answer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refine(self, request, context):
        """Service D: Refine - refines the aggregated result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finalize(self, request, context):
        """Service E: Finalize - finalizes and returns the ultimate result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=compute__pb2.ComputeRequest.FromString,
                    response_serializer=compute__pb2.ComputeResponse.SerializeToString,
            ),
            'Transform': grpc.unary_unary_rpc_method_handler(
                    servicer.Transform,
                    request_deserializer=compute__pb2.TransformRequest.FromString,
                    response_serializer=compute__pb2.TransformResponse.SerializeToString,
            ),
            'Aggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.Aggregate,
                    request_deserializer=compute__pb2.AggregateRequest.FromString,
                    response_serializer=compute__pb2.AggregateResponse.SerializeToString,
            ),
            'Refine': grpc.unary_unary_rpc_method_handler(
                    servicer.Refine,
                    request_deserializer=compute__pb2.RefineRequest.FromString,
                    response_serializer=compute__pb2.RefineResponse.SerializeToString,
            ),
            'Finalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalize,
                    request_deserializer=compute__pb2.FinalizeRequest.FromString,
                    response_serializer=compute__pb2.FinalizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.Compute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Compute(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.Compute/Compute',
            compute__pb2.ComputeRequest.SerializeToString,
            compute__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Transform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.Compute/Transform',
            compute__pb2.TransformRequest.SerializeToString,
            compute__pb2.TransformResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Aggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.Compute/Aggregate',
            compute__pb2.AggregateRequest.SerializeToString,
            compute__pb2.AggregateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Refine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.Compute/Refine',
            compute__pb2.RefineRequest.SerializeToString,
            compute__pb2.RefineResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Finalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/demo.Compute/Finalize',
            compute__pb2.FinalizeRequest.SerializeToString,
            compute__pb2.FinalizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
